name: Pull Request

on: pull_request

jobs:
  pull_request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Spigot
        run: |
          curl https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -o /tmp/BuildTools.jar
          java -jar /tmp/BuildTools.jar --rev 1.20.2 --remapped
      - name: Build
        run: ./gradlew build
